server:
  port: 1990


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/department_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: material4u@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1994/eureka/
  instance:
    hostname: localhost
